# Generated by Django 4.2.7 on 2023-12-06 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='syllabus',
            field=models.ForeignKey(default='h', on_delete=django.db.models.deletion.CASCADE, related_name='pages_by_syllabus', to='Course.syllabus'),
            preserve_default=False,
        ),
    ]
