# Generated by Django 4.2.7 on 2023-11-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0004_rename_title_course_course_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabus',
            old_name='overview',
            new_name='description',
        ),
    ]
