# Generated by Django 4.2.7 on 2023-12-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_is_premium'),
        ('Class', '0003_submission_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='classes', to='User.student'),
        ),
    ]
