# Generated by Django 4.2.4 on 2023-12-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0006_comment_user_post_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
