# Generated by Django 4.2.7 on 2023-12-10 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institution', '0001_initial'),
        ('User', '0003_user_is_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('S', 'Student'), ('T', 'Teacher'), ('C', 'Content Creator')], max_length=1),
        ),
        migrations.CreateModel(
            name='ContentCreator',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='User.user')),
                ('name', models.CharField(max_length=255)),
                ('institution_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutionID_content_creator', to='Institution.institution')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.specialization')),
            ],
            bases=('User.user',),
        ),
    ]
