# Generated by Django 4.2.7 on 2023-12-11 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_is_premium'),
        ('User', '0005_remove_contentcreator_institution_id_and_more'),
    ]

    operations = [
    ]
