# Generated by Django 4.2.8 on 2023-12-10 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_is_premium'),
        ('Subscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='SubscriptionID',
            new_name='subscriptionID',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='TypeName',
        ),
        migrations.AddField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('M', 'Monthly'), ('H', 'Half-Yearly'), ('Y', 'Yearly')], default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='User.user'),
        ),
    ]
