# Generated by Django 4.2.7 on 2023-12-06 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('InstitutionID', models.AutoField(primary_key=True, serialize=False)),
                ('InstitutionName', models.CharField(max_length=255)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('ContactNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('Subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Institutions', to='Subscription.subscription')),
            ],
        ),
    ]
