# Generated by Django 4.2.7 on 2023-12-06 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('mocktestID', models.BigAutoField(primary_key=True, serialize=False)),
                ('mocktestName', models.CharField(max_length=200)),
                ('mocktestDescription', models.TextField()),
                ('mocktestDateCreated', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.course')),
            ],
        ),
        migrations.CreateModel(
            name='MockQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=512)),
                ('choiceA', models.CharField(max_length=255, verbose_name='A')),
                ('choiceB', models.CharField(max_length=255, verbose_name='B')),
                ('choiceC', models.CharField(max_length=255, verbose_name='C')),
                ('choiceD', models.CharField(max_length=255, verbose_name='D')),
                ('subject', models.CharField(max_length=255)),
                ('correctAnswer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Correct Answer')),
                ('mocktest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mocktest.mocktest')),
            ],
        ),
        migrations.CreateModel(
            name='MockTestScores',
            fields=[
                ('mocktestScoreID', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('mocktestDateTaken', models.DateField(auto_now_add=True)),
                ('mocktestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mocktest.mocktest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.student')),
            ],
            options={
                'unique_together': {('mocktestId', 'student')},
            },
        ),
    ]
