# Generated by Django 4.2.4 on 2023-12-04 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_user_type'),
        ('Mocktest', '0002_mocktestscores_totalquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocktestscores',
            name='mocktestId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mocktest_scores', to='Mocktest.mocktest'),
        ),
        migrations.AlterField(
            model_name='mocktestscores',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='User.student'),
        ),
    ]
