# Generated by Django 4.2.4 on 2023-12-08 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('Mocktest', '0002_difficulty_mockquestions_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocktestscores',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='User.user'),
        ),
    ]
