# Generated by Django 4.2.4 on 2023-12-04 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_user_type'),
        ('Mocktest', '0003_alter_mocktestscores_mocktestid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mocktestscores',
            old_name='mocktestId',
            new_name='mocktest_id',
        ),
        migrations.AlterUniqueTogether(
            name='mocktestscores',
            unique_together={('mocktest_id', 'student')},
        ),
    ]
