# Generated by Django 4.2.4 on 2023-12-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mocktest', '0004_rename_mocktestid_mocktestscores_mocktest_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockquestions',
            name='correctAnswer',
            field=models.CharField(max_length=255, verbose_name='Correct Answer'),
        ),
    ]
