# Generated by Django 4.2.4 on 2023-12-08 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_page_syllabus'),
        ('Class', '0001_initial'),
        ('Mocktest', '0005_remove_mocktest_course_mocktest_classid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mocktest',
            name='classID',
        ),
        migrations.AddField(
            model_name='mocktest',
            name='courseTest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.course'),
        ),
        migrations.CreateModel(
            name='ClassMocktest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTaken', models.DateField(auto_now_add=True)),
                ('classInstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class.class')),
                ('mocktestInstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mocktest.mocktest')),
            ],
            options={
                'unique_together': {('classInstance', 'mocktestInstance')},
            },
        ),
    ]
