# Generated by Django 4.2.4 on 2023-12-08 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mocktest', '0006_remove_mocktest_classid_mocktest_coursetest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mocktest',
            old_name='courseTest',
            new_name='course',
        ),
    ]
