# Generated by Django 4.2.7 on 2023-12-11 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mocktest', '0005_mocktestscores_feedback'),
        ('Mocktest', '0009_alter_mockquestions_mocktest'),
    ]

    operations = [
    ]
